runtime: custom
env: flex
resources:
  cpu: 2
  memory_gb: 6
#network:
#  session_affinity: true
health_check:
  enable_health_check: false
automatic_scaling:
  min_num_instances: 1
handlers:
- url: /static
  static_dir: static
  expiration: '10s'
