runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 6
network:
  session_affinity: true
liveness_check:
  path: "/liveness_check"
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 10
  failure_threshold: 10
  app_start_timeout_sec: 1500